
/**
 * FreeIMU calibration header. Automatically generated by octave AccMagnCalib.m.
 * Do not edit manually unless you know what you are doing.
*/

// following example of calibration.h 
#define CALIBRATION_H

const int acc_off_x = -13;
const int acc_off_y = 54;
const int acc_off_z = 1670;
const float acc_scale_x = 16473.201581;
const float acc_scale_y = 16476.242591;
const float acc_scale_z = 16539.453298;
